version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.0.0
    steps:
      - checkout
      - run: 
         name: Install dependencies
         command: npm install
      - run: 
         name: Run tests
         command: npm run tests   


workflows:
  test-deploy:
    jobs:
      - test
# version: 2.1
# orbs:
#   sonarcloud: sonarsource/sonarcloud@1.1.0

# jobs:
#   build:
#     working_directory: ~/repo
#     docker:
#       - image: cimg/node:19.0.0
#     steps:
#       - checkout
#       - run: node --version
#       - run:
#           name: Update NPM
#           command: "sudo npm install -g npm@5"
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Install Dependencies
#           command: yarn install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: Run tests
#           command: npm run test
#       - sonarcloud/scan

# workflows:
#   main:
#     jobs:
#       - build:
#           context: sonarcloud

# VS Code Extension Version: 1.0.2
