version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: node version
          command: node --version

  upload_artifact:
    docker:
      - image: cimg/node:19.0.0
    working_directory: ~/demosonarqube
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Setup JFrog
          command: |
            sudo npm install -g jfrog-cli-go --unsafe-perm=true --allow-root
            jfrog config add --url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --password $ARTIFACTORY_PASSWORD --interactive=false
            jfrog --version
      - run:
          name: Upload JFrog
          command: |
            jfrog --version
            jfrog rt u "android/app/release/app-release.apk" demosonarqube-generic-local/ --url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --password $ARTIFACTORY_PASSWORD  --flat=false
workflows:
  test-deploy:
    jobs:
      - upload_artifact

