version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:19.0.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: node version
          command: node --version

  upload_artifact:
    docker:
      - image: cimg/node:19.0.0
        # auth:
        #   username: mydockerhub-user
        #   password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/demosonarqube
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Setup JFrog
          command: |
            sudo npm install -g jfrog-cli-go --unsafe-perm=true --allow-root
            jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --password $ARTIFACTORY_PASSWORD
            jfrog rt u android/app/release app-release.apk --build-name=demo_build --build-number=1.0.0
            jfrog rt bce demo_build 1.0.0
            jfrog rt bp demo_build 1.0.0
            jfrog --version
      # - run:
      #     name: Install JFrog CLI
      #     command: sudo npm install -g --unsafe-perm=true --allow-root
      # - run:
      #     name: Push to Artifactory
      #     command: jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD

workflows:
  test-deploy:
    jobs:
      - upload_artifact
# version: 2.1
# orbs:
#   sonarcloud: sonarsource/sonarcloud@1.1.0

# jobs:
#   build:
#     working_directory: ~/repo
#     docker:
#       - image: cimg/node:19.0.0
#     steps:
#       - checkout
#       - run: node --version
#       - run:
#           name: Update NPM
#           command: "sudo npm install -g npm@5"
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#       - run:
#           name: Install Dependencies
#           command: yarn install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: Run tests
#           command: npm run test
#       - sonarcloud/scan

# workflows:
#   main:
#     jobs:
#       - build:
#           context: sonarcloud

# VS Code Extension Version: 1.0.2
